name: scivision_may3
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - black=21.4b2
  - blinker=1.5 
  - brotlipy=0.7.0
  - c-ares=1.18.1 
  - certifi=2022.12.7
  - chex=0.1.6
  - cython=0.29.33 
  - detectron2=0.6=cpu_py39hd9f9f88_3 ##
  - dm-tree=0.1.7
  - expat=2.5.0 
  - flax=0.3.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.2 
  - google-auth=2.16.3 
  - huggingface_hub=0.13.3
  - importlib-resources=5.12.0
  - jax=0.2.10
  - jupyter=1.0.0
  - keras=2.10.0 
  - libcxx=15.0.7 
  - libffi=3.4.2
  - libidn2=2.3.4
  - libnghttp2=1.51.0
  - libopenblas=0.3.21
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libxcb=1.13
  - llvm-openmp=16.0.0
  - ncurses=6.3
  - numpy=1.24.2
  - onnxconverter-common=1.13.0
  - openjpeg=2.5.0
  - optax=0.1.4
  - p11-kit=0.24.1
  - pip=23.0.1 
  - pthread-stubs=0.4
  - pyjwt=2.6.0 
  - pyopenssl=23.1.0 
  - python=3.9.15
  - pytorch=1.13.1
  - readline=8.2
  - requests=2.28.2 
  - setuptools=67.6.0 
  - svt-av1=1.4.1
  - tbb=2021.8.0
  - tensorboard=2.10.1 
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0 
  - tensorflow-cpu=2.10.0 
  - tensorflow-estimator=2.10.0 
  - tensorflow-hub=0.12.0
  - termcolor=2.2.0 
  - tf2onnx=1.13.0
  - timm=0.6.11
  - tk=8.6.12
  - tokenizers=0.12.1
  - toolz=0.12.0
  - torchvision=0.12.0
  - transformers=4.19.0
  - tzdata=2023b 
  - urllib3=1.26.15
  - werkzeug=2.2.3 
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yarl=1.8.2 
  - pip:
      - asciitree==0.3.3
      - brotli==1.0.9
      - cftime==1.6.2
      - cssselect2==0.7.0
      - dask==2023.3.2 
      - distinctipy==1.2.2
      - exifread==3.0.0
      - fasteners==0.18
      - fsspec==2023.3.0 
      - html5lib==1.1
      - image-classifiers==1.0.0
      - imageio==2.27.0 
      - intake==0.6.8
      - intake-xarray==0.6.1
      - keras-applications==1.0.8
      - keras-nlp==0.2.0
      - langdetect==1.0.9
      - lazy-loader==0.2
      - locket==1.0.0
      - mplcursors==0.5.2
      - netcdf4==1.6.3
      - networkx==3.0
      - numcodecs==0.11.0
      - opencv-python==4.7.0.72
      - pandas==1.5.3
      - partd==1.3.0
      - pyclipper==1.3.0.post4
      - pydantic==1.10.7
      - pydyf==0.5.0 
      - pypdfium2==3.21.1
      - pyphen==0.14.0
      - python-doctr==0.6.0
      - pytz==2023.2
      - pywavelets==1.4.1 
      - rapidfuzz==2.13.7 
      - scikit-image==0.20.0
      - scipy==1.9.1
      - shapely==1.8.5.post1
      - tensorflow-text==2.10.0 
      - tifffile==2023.3.21 
      - unidecode==1.3.6
      - weasyprint==58.1 
      - xarray==2023.3.0 
      - zarr==2.14.2
      - zopfli==0.2.2
      - git+https://github.com/alan-turing-institute/scivision@main#egg=scivision
      #- git+https://github.com/IFenton/scivision@IFenton-font-patch#egg=scivision

    
