name: scivision_may4
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - antlr-python-runtime=4.9.3
  - anyio=3.6.2
  - aom=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.0
  - black=21.4b2
  - bleach=6.0.0
  - blinker=1.5
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - chex=0.1.6  #0.1.7
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cycler=0.11.0
  - cython=0.29.33
  - dataclasses=0.8
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - detectron2=0.6=cpu_py39hd9f9f88_3
  - dm-tree=0.1.7
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=4.4.2
  - filelock=3.10.6
  - flatbuffers=2.0.8
  - flax=0.3.3 #=0.3.6
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.2
  - freetype=2.12.1
  - frozenlist=1.3.3
  - future=0.18.3
  - fvcore=0.1.5.post20221221
  - gast=0.4.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - google-auth=2.16.3
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - h5py=3.8.0
  - hdf5=1.12.2
  - huggingface_hub=0.13.3
  - hydra-core=1.3.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.1.0
  - importlib_resources=5.12.0
  - iopath=0.1.9
  - ipykernel=6.22.0
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.5
  - jax=0.2.10
  - jaxlib=0.1.74
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.6
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=7.86.0
  - libcxx=15.0.7
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.51.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=16.0.0
  - markdown=3.4.3
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2022.2.1
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.2
  - oauthlib=3.2.2
  - omegaconf=2.3.0
  - onnx=1.13.1
  - onnxconverter-common=1.13.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - optax=0.1.4
  - p11-kit=0.24.1
  - packaging=23.0
  - pandoc=3.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.11.1
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.2.0
  - ply=3.11
  - pooch=1.7.0
  - portalocker=2.7.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=4.21.12
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycocotools=2.0.6
  - pycparser=2.21
  - pydot=1.2.4
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pyopenssl=23.1.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-flatbuffers=2.0
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytorch=1.13.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.6
  - qtconsole=5.4.1
  - qtconsole-base=5.4.1
  - qtpy=2.3.0
  - re2=2022.06.01
  - readline=8.2
  - regex=2023.3.23
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rsa=4.9
  - sacremoses=0.0.53
  - send2trash=1.8.0
  - setuptools=67.6.0
  - sip=6.7.7
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-cpu=2.10.0
  - tensorflow-estimator=2.10.0
  - tensorflow-hub=0.12.0
  - termcolor=2.2.0
  - terminado=0.17.1
  - tf2onnx=1.13.0
  - timm=0.6.11
  - tinycss2=1.2.1
  - tk=8.6.12
  - tokenizers=0.12.1
  - toml=0.10.2
  - toolz=0.12.0
  - torchvision=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - transformers=4.19.0
  - typed-ast=1.5.4
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023b
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - werkzeug=2.2.3
  - wheel=0.40.0
  - widgetsnbextension=4.0.6
  - wrapt=1.15.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - asciitree==0.3.3
      - brotli==1.0.9
      - cftime==1.6.2
      - cssselect2==0.7.0
      - dask==2023.3.2
      - distinctipy==1.2.2
      - exifread==3.0.0
      - fasteners==0.18
      - fsspec==2023.3.0
      - html5lib==1.1
      #- huggingface-objectdetection==0.0.2
      #- huggingface-segmentation==0.0.1
      - image-classifiers==1.0.0
      - imageio==2.27.0
      - intake==0.6.8
      - intake-xarray==0.6.1
      - keras-applications==1.0.8
      - keras-nlp==0.2.0
      - langdetect==1.0.9
      - lazy-loader==0.2
      - locket==1.0.0
      - mplcursors==0.5.2
      - netcdf4==1.6.3
      - networkx==3.0
      - numcodecs==0.11.0
      - opencv-python==4.7.0.72
      - pandas==1.5.3
      - partd==1.3.0
      - pyclipper==1.3.0.post4
      - pydantic==1.10.7
      - pydyf==0.5.0
      - pypdfium2==3.21.1
      - pyphen==0.14.0
      - python-doctr==0.6.0
      - pytz==2023.2
      - pywavelets==1.4.1
      - rapidfuzz==2.13.7
      - scikit-image==0.20.0
      - scipy==1.9.1
      #- scivision-classifier==0.0.1
      #- scivision-huggingface==0.0.1
      - shapely==1.8.5.post1
      - tensorflow-text==2.10.0
      - tifffile==2023.3.21
      - unidecode==1.3.6
      - weasyprint==58.1
      - xarray==2023.3.0
      - zarr==2.14.2
      - zopfli==0.2.2
      #- git+https://github.com/alan-turing-institute/scivision@main#egg=scivision
      - git+https://github.com/IFenton/scivision@IFenton-font-patch#egg=scivision
    
